Fix for papilio-prog compilation failure under Ubuntu(gcc 6.2.0).
The code was not compiling under ubuntu 16.10 that contains a fairely recent
gcc (6.2.0). The code bellow does minimal changes to make it compile again.

The errors where the following:
ioftdi.cpp: In constructor ‘IOFtdi::IOFtdi(int, int, const char*, const char*, int)’:
ioftdi.cpp:113:67: error: narrowing conversion of ‘-5’ from ‘int’ to ‘unsigned char’ inside { } [-Wnarrowing]
                                         SET_BITS_HIGH, ~0x04, 0x04};
                                                                   ^
ioftdi.cpp: In member function ‘virtual void IOFtdi::tx_tms(unsigned char*, int)’:
ioftdi.cpp:244:92: warning: narrowing conversion of ‘(length - 1)’ from ‘int’ to ‘unsigned char’ inside { } [-Wnarrowing]
     unsigned char buf[3] = {MPSSE_WRITE_TMS|MPSSE_LSB|MPSSE_BITMODE|MPSSE_WRITE_NEG, length-1, pat[0]};
                                                                                      ~~~~~~^~